<?php
namespace Dsinn\SrcomApi\Tests;

class GamesTest extends TestCase
{
    /**
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function testGetCategories()
    {
        $client = $this->getClient(<<<'JSON'
{
  "data":[
    {
      "id":"n2y3r8do",
      "name":"Any%",
      "weblink":"https://www.speedrun.com/sms#Any",
      "type":"per-game",
      "rules":"**Goal**\r\nBeat the game (Defeat Bowser in Corona Mountain).\r\n\r\n**Timing**\r\nTime starts when pressing A to select \u0027Yes\u0027 to create a new file. Time ends when you land the final ground pound on the Bowser fight.\r\n\r\n**Requirements**\r\n* Runs must be real-time (No pausing the timer).\r\n* When playing on console, you must play using an official game disc. USB/SD loading or unofficial (copied) discs are not allowed.\r\n* Using Nintendont to play discs from other regions is NOT allowed.\r\n* Emulator is not allowed for runs under 1 hour 35 minutes.\r\n* Video proof is required for runs under 1 hour 25 minutes.\r\n* Videos are required to show the game clearly, and contain game audio.\r\n\r\n**Recommendations**\r\n* Submit your runs with video if you have the ability to do so, regardless of the requirements.\r\n* Upload your splits to splits.io and add them to your submission, especially if you don\u0027t have a video.\r\n* [Gecko OS](http://wiibrew.org/wiki/Gecko_OS) is the preferred app for playing discs from other regions. Priiloader and AnyRegion Changer are also fine. If you want to use a different method, please contact a moderator first.\r\n* If you have any questions, contact a moderator. The best place to do this is in the [community Discord](https://discord.gg/0SoktBcRDw8B1NJB).",
      "players":{
        "type":"exactly",
        "value":1
      },
      "miscellaneous":false,
      "links":[
        {
          "rel":"self",
          "uri":"https://www.speedrun.com/api/v1/categories/n2y3r8do"
        },
        {
          "rel":"game",
          "uri":"https://www.speedrun.com/api/v1/games/v1pxjz68"
        },
        {
          "rel":"variables",
          "uri":"https://www.speedrun.com/api/v1/categories/n2y3r8do/variables"
        },
        {
          "rel":"records",
          "uri":"https://www.speedrun.com/api/v1/categories/n2y3r8do/records"
        },
        {
          "rel":"runs",
          "uri":"https://www.speedrun.com/api/v1/runs?category=n2y3r8do"
        },
        {
          "rel":"leaderboard",
          "uri":"https://www.speedrun.com/api/v1/leaderboards/v1pxjz68/category/n2y3r8do"
        }
      ],
      "game":{
        "data":{
          "id":"v1pxjz68",
          "names":{
            "international":"Super Mario Sunshine",
            "japanese":"\u30b9\u30fc\u30d1\u30fc\u30de\u30ea\u30aa\u30b5\u30f3\u30b7\u30e3\u30a4\u30f3",
            "twitch":"Super Mario Sunshine"
          },
          "abbreviation":"sms",
          "weblink":"https://www.speedrun.com/sms",
          "released":2002,
          "release-date":"2002-07-19",
          "ruleset":{
            "show-milliseconds":true,
            "require-verification":true,
            "require-video":false,
            "run-times":[
              "realtime",
              "ingame"
            ],
            "default-time":"realtime",
            "emulators-allowed":true
          },
          "romhack":false,
          "gametypes":[

          ],
          "platforms":[
            "4p9z06rn",
            "v06dk3e4"
          ],
          "regions":[
            "pr184lqn",
            "e6lxy1dz",
            "o316x197",
            "p2g50lnk"
          ],
          "genres":[
            "qdnqkn8k",
            "jp23ox26"
          ],
          "engines":[

          ],
          "developers":[
            "xv6dvx62"
          ],
          "publishers":[
            "m0rvylrx"
          ],
          "moderators":{
            "dkjplk8q":"super-moderator",
            "qj2w9ojk":"super-moderator",
            "qjopynx6":"super-moderator",
            "y8d44o86":"super-moderator",
            "y8d41986":"super-moderator",
            "o8639p8z":"super-moderator",
            "18v6knxl":"super-moderator",
            "qj2367xk":"super-moderator",
            "98r36381":"super-moderator",
            "qj2y1r68":"super-moderator",
            "0jml7ly8":"super-moderator",
            "kj9k3lr8":"super-moderator"
          },
          "created":"2014-12-07T12:50:20Z",
          "assets":{
            "logo":{
              "uri":"https://www.speedrun.com/themes/sms/logo.png",
              "width":180,
              "height":32
            },
            "cover-tiny":{
              "uri":"https://www.speedrun.com/themes/sms/cover-32.png",
              "width":32,
              "height":45
            },
            "cover-small":{
              "uri":"https://www.speedrun.com/themes/sms/cover-64.png",
              "width":64,
              "height":90
            },
            "cover-medium":{
              "uri":"https://www.speedrun.com/themes/sms/cover-128.png",
              "width":128,
              "height":180
            },
            "cover-large":{
              "uri":"https://www.speedrun.com/themes/sms/cover-256.png",
              "width":256,
              "height":360
            },
            "icon":{
              "uri":"https://www.speedrun.com/themes/sms/favicon.png",
              "width":282,
              "height":325
            },
            "trophy-1st":{
              "uri":"https://www.speedrun.com/themes/sms/1st.png",
              "width":18,
              "height":18
            },
            "trophy-2nd":{
              "uri":"https://www.speedrun.com/themes/sms/2nd.png",
              "width":18,
              "height":18
            },
            "trophy-3rd":{
              "uri":"https://www.speedrun.com/themes/sms/3rd.png",
              "width":18,
              "height":18
            },
            "trophy-4th":null,
            "background":{
              "uri":"https://www.speedrun.com/themes/sms/background.png",
              "width":1920,
              "height":1080
            },
            "foreground":null
          },
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/games/v1pxjz68"
            },
            {
              "rel":"runs",
              "uri":"https://www.speedrun.com/api/v1/runs?game=v1pxjz68"
            },
            {
              "rel":"levels",
              "uri":"https://www.speedrun.com/api/v1/games/v1pxjz68/levels"
            },
            {
              "rel":"categories",
              "uri":"https://www.speedrun.com/api/v1/games/v1pxjz68/categories"
            },
            {
              "rel":"variables",
              "uri":"https://www.speedrun.com/api/v1/games/v1pxjz68/variables"
            },
            {
              "rel":"records",
              "uri":"https://www.speedrun.com/api/v1/games/v1pxjz68/records"
            },
            {
              "rel":"series",
              "uri":"https://www.speedrun.com/api/v1/series/rv7emz49"
            },
            {
              "rel":"derived-games",
              "uri":"https://www.speedrun.com/api/v1/games/v1pxjz68/derived-games"
            },
            {
              "rel":"romhacks",
              "uri":"https://www.speedrun.com/api/v1/games/v1pxjz68/derived-games"
            },
            {
              "rel":"leaderboard",
              "uri":"https://www.speedrun.com/api/v1/leaderboards/v1pxjz68/category/n2y3r8do"
            }
          ]
        }
      },
      "variables":{
        "data":[
          {
            "id":"kn0m2zl3",
            "name":"Normal/Hoverless",
            "category":"n2y3r8do",
            "scope":{
              "type":"full-game"
            },
            "mandatory":true,
            "user-defined":false,
            "obsoletes":true,
            "values":{
              "_note":"`choices` is deprecated, please use `values` instead",
              "choices":{
                "jq6m9o1m":"Normal",
                "5lmyr0lv":"Hoverless"
              },
              "values":{
                "jq6m9o1m":{
                  "label":"Normal",
                  "rules":null,
                  "flags":{
                    "miscellaneous":false
                  }
                },
                "5lmyr0lv":{
                  "label":"Hoverless",
                  "rules":"Hover-Nozzle is banned.",
                  "flags":{
                    "miscellaneous":false
                  }
                }
              },
              "default":"jq6m9o1m"
            },
            "is-subcategory":true,
            "links":[
              {
                "rel":"self",
                "uri":"https://www.speedrun.com/api/v1/variables/kn0m2zl3"
              },
              {
                "rel":"game",
                "uri":"https://www.speedrun.com/api/v1/games/v1pxjz68"
              },
              {
                "rel":"category",
                "uri":"https://www.speedrun.com/api/v1/categories/n2y3r8do"
              }
            ]
          }
        ]
      }
    },
    {
      "id":"wkpmjjkr",
      "name":"All Episodes",
      "weblink":"https://www.speedrun.com/sms#All_Episodes",
      "type":"per-game",
      "rules":"**Goal**\r\nCollect every Shine Sprite obtained from completing episodes in the game worlds (8 per world), and beat the game (Defeat Bowser in Corona Mountain), for a grand total of 58 Shine Sprites.\r\n\r\n**Timing**\r\nTime starts when pressing A to select \u0027Yes\u0027 to create a new file. Time ends when you land the final ground pound on the Bowser fight.\r\n\r\n**Requirements**\r\n* Runs must be real-time (No pausing the timer).\r\n* When playing on console, you must play using an official game disc. USB/SD loading or unofficial (copied) discs are not allowed.\r\n* Using Nintendont to play discs from other regions is NOT allowed.\r\n* Emulator is not allowed for runs under 1 hour 50 minutes.\r\n* Video proof is required for runs under 1 hour 50 minutes.\r\n* Videos are required to show the game clearly, and contain game audio.\r\n\r\n**Recommendations**\r\n* Submit your runs with video if you have the ability to do so, regardless of the requirements.\r\n* Upload your splits to splits.io and add them to your submission, especially if you don\u0027t have a video.\r\n* [Gecko OS](http://wiibrew.org/wiki/Gecko_OS) is the preferred app for playing discs from other regions. Priiloader and AnyRegion Changer are also fine. If you want to use a different method, please contact a moderator first.\r\n* If you have any questions, contact a moderator. The best place to do this is in the [community Discord](https://discord.gg/0SoktBcRDw8B1NJB).",
      "players":{
        "type":"exactly",
        "value":1
      },
      "miscellaneous":false,
      "links":[
        {
          "rel":"self",
          "uri":"https://www.speedrun.com/api/v1/categories/wkpmjjkr"
        },
        {
          "rel":"game",
          "uri":"https://www.speedrun.com/api/v1/games/v1pxjz68"
        },
        {
          "rel":"variables",
          "uri":"https://www.speedrun.com/api/v1/categories/wkpmjjkr/variables"
        },
        {
          "rel":"records",
          "uri":"https://www.speedrun.com/api/v1/categories/wkpmjjkr/records"
        },
        {
          "rel":"runs",
          "uri":"https://www.speedrun.com/api/v1/runs?category=wkpmjjkr"
        },
        {
          "rel":"leaderboard",
          "uri":"https://www.speedrun.com/api/v1/leaderboards/v1pxjz68/category/wkpmjjkr"
        }
      ],
      "game":{
        "data":{
          "id":"v1pxjz68",
          "names":{
            "international":"Super Mario Sunshine",
            "japanese":"\u30b9\u30fc\u30d1\u30fc\u30de\u30ea\u30aa\u30b5\u30f3\u30b7\u30e3\u30a4\u30f3",
            "twitch":"Super Mario Sunshine"
          },
          "abbreviation":"sms",
          "weblink":"https://www.speedrun.com/sms",
          "released":2002,
          "release-date":"2002-07-19",
          "ruleset":{
            "show-milliseconds":true,
            "require-verification":true,
            "require-video":false,
            "run-times":[
              "realtime",
              "ingame"
            ],
            "default-time":"realtime",
            "emulators-allowed":true
          },
          "romhack":false,
          "gametypes":[

          ],
          "platforms":[
            "4p9z06rn",
            "v06dk3e4"
          ],
          "regions":[
            "pr184lqn",
            "e6lxy1dz",
            "o316x197",
            "p2g50lnk"
          ],
          "genres":[
            "qdnqkn8k",
            "jp23ox26"
          ],
          "engines":[

          ],
          "developers":[
            "xv6dvx62"
          ],
          "publishers":[
            "m0rvylrx"
          ],
          "moderators":{
            "dkjplk8q":"super-moderator",
            "qj2w9ojk":"super-moderator",
            "qjopynx6":"super-moderator",
            "y8d44o86":"super-moderator",
            "y8d41986":"super-moderator",
            "o8639p8z":"super-moderator",
            "18v6knxl":"super-moderator",
            "qj2367xk":"super-moderator",
            "98r36381":"super-moderator",
            "qj2y1r68":"super-moderator",
            "0jml7ly8":"super-moderator",
            "kj9k3lr8":"super-moderator"
          },
          "created":"2014-12-07T12:50:20Z",
          "assets":{
            "logo":{
              "uri":"https://www.speedrun.com/themes/sms/logo.png",
              "width":180,
              "height":32
            },
            "cover-tiny":{
              "uri":"https://www.speedrun.com/themes/sms/cover-32.png",
              "width":32,
              "height":45
            },
            "cover-small":{
              "uri":"https://www.speedrun.com/themes/sms/cover-64.png",
              "width":64,
              "height":90
            },
            "cover-medium":{
              "uri":"https://www.speedrun.com/themes/sms/cover-128.png",
              "width":128,
              "height":180
            },
            "cover-large":{
              "uri":"https://www.speedrun.com/themes/sms/cover-256.png",
              "width":256,
              "height":360
            },
            "icon":{
              "uri":"https://www.speedrun.com/themes/sms/favicon.png",
              "width":282,
              "height":325
            },
            "trophy-1st":{
              "uri":"https://www.speedrun.com/themes/sms/1st.png",
              "width":18,
              "height":18
            },
            "trophy-2nd":{
              "uri":"https://www.speedrun.com/themes/sms/2nd.png",
              "width":18,
              "height":18
            },
            "trophy-3rd":{
              "uri":"https://www.speedrun.com/themes/sms/3rd.png",
              "width":18,
              "height":18
            },
            "trophy-4th":null,
            "background":{
              "uri":"https://www.speedrun.com/themes/sms/background.png",
              "width":1920,
              "height":1080
            },
            "foreground":null
          },
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/games/v1pxjz68"
            },
            {
              "rel":"runs",
              "uri":"https://www.speedrun.com/api/v1/runs?game=v1pxjz68"
            },
            {
              "rel":"levels",
              "uri":"https://www.speedrun.com/api/v1/games/v1pxjz68/levels"
            },
            {
              "rel":"categories",
              "uri":"https://www.speedrun.com/api/v1/games/v1pxjz68/categories"
            },
            {
              "rel":"variables",
              "uri":"https://www.speedrun.com/api/v1/games/v1pxjz68/variables"
            },
            {
              "rel":"records",
              "uri":"https://www.speedrun.com/api/v1/games/v1pxjz68/records"
            },
            {
              "rel":"series",
              "uri":"https://www.speedrun.com/api/v1/series/rv7emz49"
            },
            {
              "rel":"derived-games",
              "uri":"https://www.speedrun.com/api/v1/games/v1pxjz68/derived-games"
            },
            {
              "rel":"romhacks",
              "uri":"https://www.speedrun.com/api/v1/games/v1pxjz68/derived-games"
            },
            {
              "rel":"leaderboard",
              "uri":"https://www.speedrun.com/api/v1/leaderboards/v1pxjz68/category/n2y3r8do"
            }
          ]
        }
      },
      "variables":{
        "data":[
          {
            "id":"0nw7908q",
            "name":"Normal/Hoverless",
            "category":"wkpmjjkr",
            "scope":{
              "type":"full-game"
            },
            "mandatory":true,
            "user-defined":false,
            "obsoletes":true,
            "values":{
              "_note":"`choices` is deprecated, please use `values` instead",
              "choices":{
                "rqv7kyq6":"Normal",
                "814jok1d":"Hoverless"
              },
              "values":{
                "rqv7kyq6":{
                  "label":"Normal",
                  "rules":null,
                  "flags":{
                    "miscellaneous":null
                  }
                },
                "814jok1d":{
                  "label":"Hoverless",
                  "rules":"Hover-Nozzle is banned.",
                  "flags":{
                    "miscellaneous":false
                  }
                }
              },
              "default":"rqv7kyq6"
            },
            "is-subcategory":true,
            "links":[
              {
                "rel":"self",
                "uri":"https://www.speedrun.com/api/v1/variables/0nw7908q"
              },
              {
                "rel":"game",
                "uri":"https://www.speedrun.com/api/v1/games/v1pxjz68"
              },
              {
                "rel":"category",
                "uri":"https://www.speedrun.com/api/v1/categories/wkpmjjkr"
              }
            ]
          }
        ]
      }
    }
  ]
}
JSON
        );
        $categories = $client->games()->getCategories('foo');

        self::assertSame('Any%', $categories[0]->getName());
        self::assertSame('All Episodes', $categories[1]->getName());
    }
}
