<?php
namespace Dsinn\SrcomApi\Tests;

class LeaderboardsTest extends TestCase
{
    /**
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function testGetByGameCategory()
    {
        $client = $this->getClient(<<<'JSON'
{
  "data":{
    "weblink":"https://www.speedrun.com/aoe2/full_game#All_Campaigns",
    "game":{
      "data":{
        "id":"xldev513",
        "names":{
          "international":"Age of Empires II",
          "japanese":null,
          "twitch":"Age of Empires II"
        },
        "abbreviation":"aoe2",
        "weblink":"https://www.speedrun.com/aoe2",
        "released":1999,
        "release-date":"1999-09-30",
        "ruleset":{
          "show-milliseconds":false,
          "require-verification":true,
          "require-video":true,
          "run-times":[
            "realtime"
          ],
          "default-time":"realtime",
          "emulators-allowed":true
        },
        "romhack":false,
        "gametypes":[

        ],
        "platforms":[
          "n5e17e27",
          "8gej2n93"
        ],
        "regions":[

        ],
        "genres":[
          "jp23mxn6"
        ],
        "engines":[
          "v93d7m3y"
        ],
        "developers":[
          "5yz87g6w"
        ],
        "publishers":[
          "4dnll7nl"
        ],
        "moderators":{
          "gpj0mxwr":"super-moderator",
          "v18q6wjn":"super-moderator",
          "y0jm0e81":"super-moderator",
          "qj29poxk":"super-moderator"
        },
        "created":null,
        "assets":{
          "logo":{
            "uri":"https://www.speedrun.com/themes/aoe2/logo.png",
            "width":180,
            "height":32
          },
          "cover-tiny":{
            "uri":"https://www.speedrun.com/themes/aoe2/cover-32.png",
            "width":32,
            "height":45
          },
          "cover-small":{
            "uri":"https://www.speedrun.com/themes/aoe2/cover-64.png",
            "width":64,
            "height":90
          },
          "cover-medium":{
            "uri":"https://www.speedrun.com/themes/aoe2/cover-128.png",
            "width":128,
            "height":180
          },
          "cover-large":{
            "uri":"https://www.speedrun.com/themes/aoe2/cover-256.png",
            "width":256,
            "height":360
          },
          "icon":{
            "uri":"https://www.speedrun.com/themes/aoe2/favicon.png",
            "width":48,
            "height":48
          },
          "trophy-1st":{
            "uri":"https://www.speedrun.com/themes/Default/1st.png",
            "width":64,
            "height":64
          },
          "trophy-2nd":{
            "uri":"https://www.speedrun.com/themes/Default/2nd.png",
            "width":64,
            "height":64
          },
          "trophy-3rd":{
            "uri":"https://www.speedrun.com/themes/Default/3rd.png",
            "width":64,
            "height":64
          },
          "trophy-4th":null,
          "background":{
            "uri":"https://www.speedrun.com/themes/aoe2/background.png",
            "width":1920,
            "height":1080
          },
          "foreground":null
        },
        "links":[
          {
            "rel":"self",
            "uri":"https://www.speedrun.com/api/v1/games/xldev513"
          },
          {
            "rel":"runs",
            "uri":"https://www.speedrun.com/api/v1/runs?game=xldev513"
          },
          {
            "rel":"levels",
            "uri":"https://www.speedrun.com/api/v1/games/xldev513/levels"
          },
          {
            "rel":"categories",
            "uri":"https://www.speedrun.com/api/v1/games/xldev513/categories"
          },
          {
            "rel":"variables",
            "uri":"https://www.speedrun.com/api/v1/games/xldev513/variables"
          },
          {
            "rel":"records",
            "uri":"https://www.speedrun.com/api/v1/games/xldev513/records"
          },
          {
            "rel":"series",
            "uri":"https://www.speedrun.com/api/v1/series/yr4gy141"
          },
          {
            "rel":"derived-games",
            "uri":"https://www.speedrun.com/api/v1/games/xldev513/derived-games"
          },
          {
            "rel":"romhacks",
            "uri":"https://www.speedrun.com/api/v1/games/xldev513/derived-games"
          }
        ]
      }
    },
    "category":{
      "data":{
        "id":"rklg3rdn",
        "name":"All Campaigns",
        "weblink":"https://www.speedrun.com/aoe2/full_game#All_Campaigns",
        "type":"per-game",
        "rules":"Timing starts when the first scenario has finished loading, and ends when the \u0022You Are Victorious!\u0022 text appears on the final scenario. \r\n\r\nBe sure that you have completed all the scenarios in every campaign, including The Conquerors campaigns. **THIS DOES NOT INCLUDE AoE2HD EXCLUSIVE CAMPAIGNS.**\r\n\r\nDifficulty may be changed throughout the run.\r\n\r\nRuns use real time that has passed from start to finish rather than in-game time.\r\n\r\nThe in-game speed may not be set beyond 2.0, as that feature is exclusive to the HD release.",
        "players":{
          "type":"exactly",
          "value":1
        },
        "miscellaneous":false,
        "links":[
          {
            "rel":"self",
            "uri":"https://www.speedrun.com/api/v1/categories/rklg3rdn"
          },
          {
            "rel":"game",
            "uri":"https://www.speedrun.com/api/v1/games/xldev513"
          },
          {
            "rel":"variables",
            "uri":"https://www.speedrun.com/api/v1/categories/rklg3rdn/variables"
          },
          {
            "rel":"records",
            "uri":"https://www.speedrun.com/api/v1/categories/rklg3rdn/records"
          },
          {
            "rel":"runs",
            "uri":"https://www.speedrun.com/api/v1/runs?category=rklg3rdn"
          },
          {
            "rel":"leaderboard",
            "uri":"https://www.speedrun.com/api/v1/leaderboards/xldev513/category/rklg3rdn"
          }
        ]
      }
    },
    "level":{
      "data":[

      ]
    },
    "platform":null,
    "region":null,
    "emulators":null,
    "video-only":false,
    "timing":"realtime",
    "values":{

    },
    "runs":[
      {
        "place":1,
        "run":{
          "id":"yw1nj0nz",
          "weblink":"https://www.speedrun.com/aoe2/run/yw1nj0nz",
          "game":"xldev513",
          "level":null,
          "category":"rklg3rdn",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=F1z59gYX7Jk"
              }
            ]
          },
          "comment":"Bad levels:\r\nJoA5 - Transport ship never landed, so no trigger for the end never loaded?\r\nSala2 - Bad ships\r\nBB3  - Myself playing super bad\r\nAtt1 -  Destroy monastery then market. noted.\r\nMonte 2 - Bad luck on the red army killing my rams and bad play.\r\nHastings - Needed to play it on AoE2HD not AoC\r\nVindlandsaga - Longboats wrecked me.",
          "status":{
            "status":"verified",
            "examiner":"v18q6wjn",
            "verify-date":"2018-01-05T03:22:57Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"18vqvejl",
              "uri":"https://www.speedrun.com/api/v1/users/18vqvejl"
            }
          ],
          "date":"2018-01-02",
          "submitted":"2018-01-02T22:04:03Z",
          "times":{
            "primary":"PT7H3M43S",
            "primary_t":25423,
            "realtime":"PT7H3M43S",
            "realtime_t":25423,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":{
            "rel":"splits.io",
            "uri":"https://splits.io/api/v3/runs/23gp"
          },
          "values":{
            "m5ly6jn4":"xqke89q9"
          }
        }
      },
      {
        "place":2,
        "run":{
          "id":"pzgkj6ey",
          "weblink":"https://www.speedrun.com/aoe2/run/pzgkj6ey",
          "game":"xldev513",
          "level":null,
          "category":"rklg3rdn",
          "videos":{
            "links":[
              {
                "uri":"http://www.twitch.tv/adam_ak/v/4191464"
              },
              {
                "uri":"http://www.twitch.tv/adam_ak/v/4191449"
              }
            ]
          },
          "comment":"part 2: http://www.twitch.tv/adam_ak/v/4191464\r\n\r\nResult of the race with Mhmd and Dawned. Montezuma and BoC were a mess -- rest was OK. Will improve :v)",
          "status":{
            "status":"verified",
            "examiner":"v18q6wjn",
            "verify-date":"2015-05-10T12:09:40Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"gpj0mxwr",
              "uri":"https://www.speedrun.com/api/v1/users/gpj0mxwr"
            }
          ],
          "date":"2015-04-11",
          "submitted":"2015-04-20T13:41:10Z",
          "times":{
            "primary":"PT27H55M24S",
            "primary_t":100524,
            "realtime":"PT27H55M24S",
            "realtime_t":100524,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "m5ly6jn4":"p12z471x"
          }
        }
      }
    ],
    "links":[
      {
        "rel":"game",
        "uri":"https://www.speedrun.com/api/v1/games/xldev513"
      },
      {
        "rel":"category",
        "uri":"https://www.speedrun.com/api/v1/categories/rklg3rdn"
      }
    ],
    "players":{
      "data":[
        {
          "rel":"user",
          "id":"18vqvejl",
          "names":{
            "international":"Chazb",
            "japanese":null
          },
          "weblink":"https://www.speedrun.com/user/Chazb",
          "name-style":{
            "style":"gradient",
            "color-from":{
              "light":"#808080",
              "dark":"#B8B8B8"
            },
            "color-to":{
              "light":"#808080",
              "dark":"#B8B8B8"
            }
          },
          "role":"user",
          "signup":"2015-05-21T20:33:47Z",
          "location":{
            "country":{
              "code":"gb/eng",
              "names":{
                "international":"England",
                "japanese":null
              }
            }
          },
          "twitch":{
            "uri":"https://www.twitch.tv/ChazB"
          },
          "hitbox":null,
          "youtube":{
            "uri":"https://www.youtube.com/user/Chazzybl7"
          },
          "twitter":null,
          "speedrunslive":null,
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/users/18vqvejl"
            },
            {
              "rel":"runs",
              "uri":"https://www.speedrun.com/api/v1/runs?user=18vqvejl"
            },
            {
              "rel":"games",
              "uri":"https://www.speedrun.com/api/v1/games?moderator=18vqvejl"
            },
            {
              "rel":"personal-bests",
              "uri":"https://www.speedrun.com/api/v1/users/18vqvejl/personal-bests"
            }
          ]
        },
        {
          "rel":"user",
          "id":"gpj0mxwr",
          "names":{
            "international":"Adam_ak",
            "japanese":null
          },
          "weblink":"https://www.speedrun.com/user/Adam_ak",
          "name-style":{
            "style":"gradient",
            "color-from":{
              "light":"#7AB941",
              "dark":"#8AC951"
            },
            "color-to":{
              "light":"#7AB941",
              "dark":"#8AC951"
            }
          },
          "role":"user",
          "signup":"2014-03-25T02:07:48Z",
          "location":null,
          "twitch":{
            "uri":"https://www.twitch.tv/adam_ak"
          },
          "hitbox":null,
          "youtube":{
            "uri":"https://www.youtube.com/user/AdamKuczynski"
          },
          "twitter":{
            "uri":"https://www.twitter.com/AdamKuczynski"
          },
          "speedrunslive":{
            "uri":"http://www.speedrunslive.com/profiles/#!/Adam"
          },
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/users/gpj0mxwr"
            },
            {
              "rel":"runs",
              "uri":"https://www.speedrun.com/api/v1/runs?user=gpj0mxwr"
            },
            {
              "rel":"games",
              "uri":"https://www.speedrun.com/api/v1/games?moderator=gpj0mxwr"
            },
            {
              "rel":"personal-bests",
              "uri":"https://www.speedrun.com/api/v1/users/gpj0mxwr/personal-bests"
            }
          ]
        }
      ]
    },
    "regions":{
      "data":[

      ]
    },
    "platforms":{
      "data":[
        {
          "id":"8gej2n93",
          "name":"PC",
          "released":1970,
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/platforms/8gej2n93"
            },
            {
              "rel":"games",
              "uri":"https://www.speedrun.com/api/v1/games?platform=8gej2n93"
            },
            {
              "rel":"runs",
              "uri":"https://www.speedrun.com/api/v1/runs?platform=8gej2n93"
            }
          ]
        }
      ]
    },
    "variables":{
      "data":[
        {
          "id":"m5ly6jn4",
          "name":"Game Version",
          "category":null,
          "scope":{
            "type":"full-game"
          },
          "mandatory":true,
          "user-defined":false,
          "obsoletes":true,
          "values":{
            "_note":"`choices` is deprecated, please use `values` instead",
            "choices":{
              "81pyne17":"AoK",
              "xqke89q9":"AoC",
              "p12z471x":"HD Edition",
              "gq72evd1":"UserPatch 1.4"
            },
            "values":{
              "81pyne17":{
                "label":"AoK"
              },
              "xqke89q9":{
                "label":"AoC"
              },
              "p12z471x":{
                "label":"HD Edition"
              },
              "gq72evd1":{
                "label":"UserPatch 1.4"
              }
            },
            "default":null
          },
          "is-subcategory":false,
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/variables/m5ly6jn4"
            },
            {
              "rel":"game",
              "uri":"https://www.speedrun.com/api/v1/games/xldev513"
            }
          ]
        }
      ]
    }
  }
}
JSON
        );
        $leaderboard = $client->leaderboards()->getByGameCategory('foo', 'bar');

        self::assertSame('yw1nj0nz', $leaderboard->getRuns()[0]->getRun()->getId());
        self::assertSame('pzgkj6ey', $leaderboard->getRuns()[1]->getRun()->getId());
    }

    /**
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function testGetByLevelCategory()
    {
        $client = $this->getClient(<<<'JSON'
{
  "data":{
    "weblink":"https://www.speedrun.com/aoe2/William_Wallace_Marching_and_Fighting#Standard",
    "game":{
      "data":{
        "id":"xldev513",
        "names":{
          "international":"Age of Empires II",
          "japanese":null,
          "twitch":"Age of Empires II"
        },
        "abbreviation":"aoe2",
        "weblink":"https://www.speedrun.com/aoe2",
        "released":1999,
        "release-date":"1999-09-30",
        "ruleset":{
          "show-milliseconds":false,
          "require-verification":true,
          "require-video":true,
          "run-times":[
            "realtime"
          ],
          "default-time":"realtime",
          "emulators-allowed":true
        },
        "romhack":false,
        "gametypes":[

        ],
        "platforms":[
          "n5e17e27",
          "8gej2n93"
        ],
        "regions":[

        ],
        "genres":[
          "jp23mxn6"
        ],
        "engines":[
          "v93d7m3y"
        ],
        "developers":[
          "5yz87g6w"
        ],
        "publishers":[
          "4dnll7nl"
        ],
        "moderators":{
          "gpj0mxwr":"super-moderator",
          "v18q6wjn":"super-moderator",
          "y0jm0e81":"super-moderator",
          "qj29poxk":"super-moderator"
        },
        "created":null,
        "assets":{
          "logo":{
            "uri":"https://www.speedrun.com/themes/aoe2/logo.png",
            "width":180,
            "height":32
          },
          "cover-tiny":{
            "uri":"https://www.speedrun.com/themes/aoe2/cover-32.png",
            "width":32,
            "height":45
          },
          "cover-small":{
            "uri":"https://www.speedrun.com/themes/aoe2/cover-64.png",
            "width":64,
            "height":90
          },
          "cover-medium":{
            "uri":"https://www.speedrun.com/themes/aoe2/cover-128.png",
            "width":128,
            "height":180
          },
          "cover-large":{
            "uri":"https://www.speedrun.com/themes/aoe2/cover-256.png",
            "width":256,
            "height":360
          },
          "icon":{
            "uri":"https://www.speedrun.com/themes/aoe2/favicon.png",
            "width":48,
            "height":48
          },
          "trophy-1st":{
            "uri":"https://www.speedrun.com/themes/Default/1st.png",
            "width":64,
            "height":64
          },
          "trophy-2nd":{
            "uri":"https://www.speedrun.com/themes/Default/2nd.png",
            "width":64,
            "height":64
          },
          "trophy-3rd":{
            "uri":"https://www.speedrun.com/themes/Default/3rd.png",
            "width":64,
            "height":64
          },
          "trophy-4th":null,
          "background":{
            "uri":"https://www.speedrun.com/themes/aoe2/background.png",
            "width":1920,
            "height":1080
          },
          "foreground":null
        },
        "links":[
          {
            "rel":"self",
            "uri":"https://www.speedrun.com/api/v1/games/xldev513"
          },
          {
            "rel":"runs",
            "uri":"https://www.speedrun.com/api/v1/runs?game=xldev513"
          },
          {
            "rel":"levels",
            "uri":"https://www.speedrun.com/api/v1/games/xldev513/levels"
          },
          {
            "rel":"categories",
            "uri":"https://www.speedrun.com/api/v1/games/xldev513/categories"
          },
          {
            "rel":"variables",
            "uri":"https://www.speedrun.com/api/v1/games/xldev513/variables"
          },
          {
            "rel":"records",
            "uri":"https://www.speedrun.com/api/v1/games/xldev513/records"
          },
          {
            "rel":"series",
            "uri":"https://www.speedrun.com/api/v1/series/yr4gy141"
          },
          {
            "rel":"derived-games",
            "uri":"https://www.speedrun.com/api/v1/games/xldev513/derived-games"
          },
          {
            "rel":"romhacks",
            "uri":"https://www.speedrun.com/api/v1/games/xldev513/derived-games"
          }
        ]
      }
    },
    "category":{
      "data":{
        "id":"xk9le4k0",
        "name":"Standard",
        "weblink":"https://www.speedrun.com/aoe2",
        "type":"per-level",
        "rules":"Timing starts when the map has finished loading, and ends when the \u0022You Are Victorious!\u0022 text appears. Runs use real time that has passed from start to finish rather than in-game time.\r\n\r\nAny glitch setups requiring restarting the scenario must themselves be included in the timing.\r\n\r\nThe difficulty must be set to \u0022Standard\u0022.\r\n\r\nThe in-game speed may not be set beyond 2.0, as that feature is exclusive to the HD release.",
        "players":{
          "type":"exactly",
          "value":1
        },
        "miscellaneous":false,
        "links":[
          {
            "rel":"self",
            "uri":"https://www.speedrun.com/api/v1/categories/xk9le4k0"
          },
          {
            "rel":"game",
            "uri":"https://www.speedrun.com/api/v1/games/xldev513"
          },
          {
            "rel":"variables",
            "uri":"https://www.speedrun.com/api/v1/categories/xk9le4k0/variables"
          },
          {
            "rel":"records",
            "uri":"https://www.speedrun.com/api/v1/categories/xk9le4k0/records"
          },
          {
            "rel":"runs",
            "uri":"https://www.speedrun.com/api/v1/runs?category=xk9le4k0"
          }
        ]
      }
    },
    "level":{
      "data":{
        "id":"rdqz4kdx",
        "name":"William Wallace: Marching and Fighting",
        "weblink":"https://www.speedrun.com/aoe2/William_Wallace_Marching_and_Fighting",
        "rules":null,
        "links":[
          {
            "rel":"self",
            "uri":"https://www.speedrun.com/api/v1/levels/rdqz4kdx"
          },
          {
            "rel":"game",
            "uri":"https://www.speedrun.com/api/v1/games/xldev513"
          },
          {
            "rel":"categories",
            "uri":"https://www.speedrun.com/api/v1/levels/rdqz4kdx/categories"
          },
          {
            "rel":"variables",
            "uri":"https://www.speedrun.com/api/v1/levels/rdqz4kdx/variables"
          },
          {
            "rel":"records",
            "uri":"https://www.speedrun.com/api/v1/levels/rdqz4kdx/records"
          },
          {
            "rel":"runs",
            "uri":"https://www.speedrun.com/api/v1/runs?level=rdqz4kdx"
          },
          {
            "rel":"leaderboard",
            "uri":"https://www.speedrun.com/api/v1/leaderboards/xldev513/level/rdqz4kdx/xk9le4k0"
          }
        ]
      }
    },
    "platform":null,
    "region":null,
    "emulators":null,
    "video-only":false,
    "timing":"realtime",
    "values":{

    },
    "runs":[
      {
        "place":1,
        "run":{
          "id":"z11pewwz",
          "weblink":"https://www.speedrun.com/aoe2/run/z11pewwz",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=Lx0ug-pw7u0"
              }
            ]
          },
          "comment":"IGT 1:59",
          "status":{
            "status":"verified",
            "examiner":"v18q6wjn",
            "verify-date":"2018-11-03T16:50:18Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"18vqvejl",
              "uri":"https://www.speedrun.com/api/v1/users/18vqvejl"
            }
          ],
          "date":"2018-11-02",
          "submitted":"2018-11-02T18:41:09Z",
          "times":{
            "primary":"PT1M19S",
            "primary_t":79,
            "realtime":"PT1M19S",
            "realtime_t":79,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"p12vzvqx"
          }
        }
      },
      {
        "place":2,
        "run":{
          "id":"y6712rqm",
          "weblink":"https://www.speedrun.com/aoe2/run/y6712rqm",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://youtu.be/OG4_FuNfiKo"
              }
            ]
          },
          "comment":"Honestly, I was just going for a top 3 run, but then I realized with chaz\u0027s catchup trick using the knight and some really precise timing this was possible.",
          "status":{
            "status":"verified",
            "examiner":"v18q6wjn",
            "verify-date":"2018-05-02T00:48:03Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"dx3rnlkx",
              "uri":"https://www.speedrun.com/api/v1/users/dx3rnlkx"
            }
          ],
          "date":"2018-04-28",
          "submitted":"2018-04-28T03:29:56Z",
          "times":{
            "primary":"PT1M21S",
            "primary_t":81,
            "realtime":"PT1M21S",
            "realtime_t":81,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"p12vzvqx"
          }
        }
      },
      {
        "place":3,
        "run":{
          "id":"pydg6d0y",
          "weblink":"https://www.speedrun.com/aoe2/run/pydg6d0y",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=x3IZzh_AB7g"
              }
            ]
          },
          "comment":"2:04 IGT",
          "status":{
            "status":"verified",
            "examiner":"qj29poxk",
            "verify-date":"2016-04-24T15:53:00Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"qj29poxk",
              "uri":"https://www.speedrun.com/api/v1/users/qj29poxk"
            }
          ],
          "date":"2016-04-24",
          "submitted":"2016-04-24T15:53:00Z",
          "times":{
            "primary":"PT1M22S",
            "primary_t":82,
            "realtime":"PT1M22S",
            "realtime_t":82,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"814o2wqd"
          }
        }
      },
      {
        "place":4,
        "run":{
          "id":"y8q6v8ny",
          "weblink":"https://www.speedrun.com/aoe2/run/y8q6v8ny",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=cO4euLU2k-c"
              }
            ]
          },
          "comment":"Gracias a River y SiFly por la ruta.",
          "status":{
            "status":"verified",
            "examiner":"qj29poxk",
            "verify-date":"2017-12-15T18:07:11Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"0jm0yko8",
              "uri":"https://www.speedrun.com/api/v1/users/0jm0yko8"
            }
          ],
          "date":"2017-12-14",
          "submitted":"2017-12-15T02:18:53Z",
          "times":{
            "primary":"PT1M23S",
            "primary_t":83,
            "realtime":"PT1M23S",
            "realtime_t":83,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"p12vzvqx"
          }
        }
      },
      {
        "place":5,
        "run":{
          "id":"y8q6rvwy",
          "weblink":"https://www.speedrun.com/aoe2/run/y8q6rvwy",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=ZQWdEoUGVsY"
              }
            ]
          },
          "comment":null,
          "status":{
            "status":"verified",
            "examiner":"qj29poxk",
            "verify-date":"2017-12-14T18:26:22Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"y8dqzmj6",
              "uri":"https://www.speedrun.com/api/v1/users/y8dqzmj6"
            }
          ],
          "date":"2017-12-14",
          "submitted":"2017-12-14T03:16:49Z",
          "times":{
            "primary":"PT1M25S",
            "primary_t":85,
            "realtime":"PT1M25S",
            "realtime_t":85,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"p12vzvqx"
          }
        }
      },
      {
        "place":6,
        "run":{
          "id":"6yj06v7z",
          "weblink":"https://www.speedrun.com/aoe2/run/6yj06v7z",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://youtu.be/Fv0ZoDzodW8"
              }
            ]
          },
          "comment":"The timing wasn\u0027t perfect, will do better someday !",
          "status":{
            "status":"verified",
            "examiner":"v18q6wjn",
            "verify-date":"2017-02-23T18:44:32Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"qjn2l72j",
              "uri":"https://www.speedrun.com/api/v1/users/qjn2l72j"
            }
          ],
          "date":"2017-02-23",
          "submitted":"2017-02-23T16:19:35Z",
          "times":{
            "primary":"PT1M26S",
            "primary_t":86,
            "realtime":"PT1M26S",
            "realtime_t":86,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"p12vzvqx"
          }
        }
      },
      {
        "place":6,
        "run":{
          "id":"mrq6k64y",
          "weblink":"https://www.speedrun.com/aoe2/run/mrq6k64y",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=K0eA1AUNlv8\u0026feature=youtu.be"
              }
            ]
          },
          "comment":null,
          "status":{
            "status":"verified",
            "examiner":"v18q6wjn",
            "verify-date":"2017-09-29T22:23:19Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"v8lzdr4x",
              "uri":"https://www.speedrun.com/api/v1/users/v8lzdr4x"
            }
          ],
          "date":"2017-09-27",
          "submitted":"2017-09-27T04:40:35Z",
          "times":{
            "primary":"PT1M26S",
            "primary_t":86,
            "realtime":"PT1M26S",
            "realtime_t":86,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"p12vzvqx"
          }
        }
      },
      {
        "place":8,
        "run":{
          "id":"oy2eq97y",
          "weblink":"https://www.speedrun.com/aoe2/run/oy2eq97y",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=MUWEpqim9Ec"
              }
            ]
          },
          "comment":null,
          "status":{
            "status":"verified",
            "examiner":"qj29poxk",
            "verify-date":"2016-03-13T14:04:55Z"
          },
          "players":[
            {
              "rel":"guest",
              "name":"Sugagsr",
              "uri":"https://www.speedrun.com/api/v1/guests/Sugagsr"
            }
          ],
          "date":null,
          "submitted":"2016-03-13T14:04:55Z",
          "times":{
            "primary":"PT1M28S",
            "primary_t":88,
            "realtime":"PT1M28S",
            "realtime_t":88,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"4lx5yj12"
          }
        }
      },
      {
        "place":9,
        "run":{
          "id":"8y8q8e5y",
          "weblink":"https://www.speedrun.com/aoe2/run/8y8q8e5y",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=0dsIrnA3JJM"
              }
            ]
          },
          "comment":"not bad",
          "status":{
            "status":"verified",
            "examiner":null,
            "verify-date":null
          },
          "players":[
            {
              "rel":"user",
              "id":"v18q6wjn",
              "uri":"https://www.speedrun.com/api/v1/users/v18q6wjn"
            }
          ],
          "date":"2014-12-23",
          "submitted":"2014-12-23T10:34:56Z",
          "times":{
            "primary":"PT1M30S",
            "primary_t":90,
            "realtime":"PT1M30S",
            "realtime_t":90,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{

          }
        }
      },
      {
        "place":9,
        "run":{
          "id":"zn4png7m",
          "weblink":"https://www.speedrun.com/aoe2/run/zn4png7m",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=FyTAQN3eKJk"
              }
            ]
          },
          "comment":":(",
          "status":{
            "status":"verified",
            "examiner":"v18q6wjn",
            "verify-date":"2018-11-03T16:51:32Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"18q3o3dj",
              "uri":"https://www.speedrun.com/api/v1/users/18q3o3dj"
            }
          ],
          "date":"2018-11-02",
          "submitted":"2018-11-02T15:40:15Z",
          "times":{
            "primary":"PT1M30S",
            "primary_t":90,
            "realtime":"PT1M30S",
            "realtime_t":90,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"814o2wqd"
          }
        }
      },
      {
        "place":11,
        "run":{
          "id":"emkvqo3y",
          "weblink":"https://www.speedrun.com/aoe2/run/emkvqo3y",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=UG3Ye-Rvt80"
              }
            ]
          },
          "comment":"2:17 IGT.",
          "status":{
            "status":"verified",
            "examiner":"qj29poxk",
            "verify-date":"2016-05-13T11:03:52Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"v8141658",
              "uri":"https://www.speedrun.com/api/v1/users/v8141658"
            }
          ],
          "date":"2016-05-13",
          "submitted":"2016-05-13T10:53:43Z",
          "times":{
            "primary":"PT1M31S",
            "primary_t":91,
            "realtime":"PT1M31S",
            "realtime_t":91,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"814o2wqd"
          }
        }
      },
      {
        "place":12,
        "run":{
          "id":"z039rv8z",
          "weblink":"https://www.speedrun.com/aoe2/run/z039rv8z",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://youtu.be/NSA9sOdvHm4"
              }
            ]
          },
          "comment":null,
          "status":{
            "status":"verified",
            "examiner":"v18q6wjn",
            "verify-date":"2018-08-11T23:14:26Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"dx3l24qx",
              "uri":"https://www.speedrun.com/api/v1/users/dx3l24qx"
            }
          ],
          "date":"2018-08-09",
          "submitted":"2018-08-09T10:28:00Z",
          "times":{
            "primary":"PT1M32S",
            "primary_t":92,
            "realtime":"PT1M32S",
            "realtime_t":92,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"p12vzvqx"
          }
        }
      },
      {
        "place":13,
        "run":{
          "id":"y67299qm",
          "weblink":"https://www.speedrun.com/aoe2/run/y67299qm",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=Jyh3INk-jS4"
              }
            ]
          },
          "comment":"First ever run, just getting video/split thing sorted right now, will worry about times later! :D",
          "status":{
            "status":"verified",
            "examiner":"qj29poxk",
            "verify-date":"2017-12-16T18:30:36Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"18vyq3v8",
              "uri":"https://www.speedrun.com/api/v1/users/18vyq3v8"
            }
          ],
          "date":"2017-12-16",
          "submitted":"2017-12-16T17:31:21Z",
          "times":{
            "primary":"PT1M38S",
            "primary_t":98,
            "realtime":"PT1M38S",
            "realtime_t":98,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"p12vzvqx"
          }
        }
      },
      {
        "place":14,
        "run":{
          "id":"mr8r7x4y",
          "weblink":"https://www.speedrun.com/aoe2/run/mr8r7x4y",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=Kvm3gxE5Dhs"
              }
            ]
          },
          "comment":null,
          "status":{
            "status":"verified",
            "examiner":"v18q6wjn",
            "verify-date":"2018-11-10T20:35:29Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"e8e22d78",
              "uri":"https://www.speedrun.com/api/v1/users/e8e22d78"
            }
          ],
          "date":"2018-11-10",
          "submitted":"2018-11-10T18:38:01Z",
          "times":{
            "primary":"PT2M9S",
            "primary_t":129,
            "realtime":"PT2M9S",
            "realtime_t":129,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"4lx5yj12"
          }
        }
      }
    ],
    "links":[
      {
        "rel":"game",
        "uri":"https://www.speedrun.com/api/v1/games/xldev513"
      },
      {
        "rel":"category",
        "uri":"https://www.speedrun.com/api/v1/categories/xk9le4k0"
      },
      {
        "rel":"level",
        "uri":"https://www.speedrun.com/api/v1/levels/rdqz4kdx"
      }
    ],
    "players":{
      "data":[
        {
          "rel":"user",
          "id":"18vqvejl",
          "names":{
            "international":"Chazb",
            "japanese":null
          },
          "weblink":"https://www.speedrun.com/user/Chazb",
          "name-style":{
            "style":"gradient",
            "color-from":{
              "light":"#808080",
              "dark":"#B8B8B8"
            },
            "color-to":{
              "light":"#808080",
              "dark":"#B8B8B8"
            }
          },
          "role":"user",
          "signup":"2015-05-21T20:33:47Z",
          "location":{
            "country":{
              "code":"gb/eng",
              "names":{
                "international":"England",
                "japanese":null
              }
            }
          },
          "twitch":{
            "uri":"https://www.twitch.tv/ChazB"
          },
          "hitbox":null,
          "youtube":{
            "uri":"https://www.youtube.com/user/Chazzybl7"
          },
          "twitter":null,
          "speedrunslive":null,
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/users/18vqvejl"
            },
            {
              "rel":"runs",
              "uri":"https://www.speedrun.com/api/v1/runs?user=18vqvejl"
            },
            {
              "rel":"games",
              "uri":"https://www.speedrun.com/api/v1/games?moderator=18vqvejl"
            },
            {
              "rel":"personal-bests",
              "uri":"https://www.speedrun.com/api/v1/users/18vqvejl/personal-bests"
            }
          ]
        },
        {
          "rel":"user",
          "id":"dx3rnlkx",
          "names":{
            "international":"JoeyCapollo",
            "japanese":null
          },
          "weblink":"https://www.speedrun.com/user/JoeyCapollo",
          "name-style":{
            "style":"gradient",
            "color-from":{
              "light":"#009856",
              "dark":"#09B876"
            },
            "color-to":{
              "light":"#009856",
              "dark":"#09B876"
            }
          },
          "role":"user",
          "signup":"2017-12-10T21:16:44Z",
          "location":{
            "country":{
              "code":"us",
              "names":{
                "international":"United States",
                "japanese":null
              }
            },
            "region":{
              "code":"us/in",
              "names":{
                "international":"Indiana, USA",
                "japanese":null
              }
            }
          },
          "twitch":null,
          "hitbox":null,
          "youtube":{
            "uri":"https://www.youtube.com/channel/UCdpzUPsovyzIUUqn835FuqA"
          },
          "twitter":null,
          "speedrunslive":null,
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/users/dx3rnlkx"
            },
            {
              "rel":"runs",
              "uri":"https://www.speedrun.com/api/v1/runs?user=dx3rnlkx"
            },
            {
              "rel":"games",
              "uri":"https://www.speedrun.com/api/v1/games?moderator=dx3rnlkx"
            },
            {
              "rel":"personal-bests",
              "uri":"https://www.speedrun.com/api/v1/users/dx3rnlkx/personal-bests"
            }
          ]
        },
        {
          "rel":"user",
          "id":"qj29poxk",
          "names":{
            "international":"SiFly",
            "japanese":null
          },
          "weblink":"https://www.speedrun.com/user/SiFly",
          "name-style":{
            "style":"gradient",
            "color-from":{
              "light":"#000000",
              "dark":"#FFFFFF"
            },
            "color-to":{
              "light":"#000000",
              "dark":"#FFFFFF"
            }
          },
          "role":"user",
          "signup":"2015-04-17T16:04:17Z",
          "location":{
            "country":{
              "code":"nl",
              "names":{
                "international":"Netherlands",
                "japanese":null
              }
            }
          },
          "twitch":{
            "uri":"https://www.twitch.tv/SiFlyy"
          },
          "hitbox":null,
          "youtube":{
            "uri":"https://www.youtube.com/channel/UCpvpDc9vVui-D2ITJtoK4mg"
          },
          "twitter":{
            "uri":"https://www.twitter.com/AoCSpeedruns"
          },
          "speedrunslive":null,
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/users/qj29poxk"
            },
            {
              "rel":"runs",
              "uri":"https://www.speedrun.com/api/v1/runs?user=qj29poxk"
            },
            {
              "rel":"games",
              "uri":"https://www.speedrun.com/api/v1/games?moderator=qj29poxk"
            },
            {
              "rel":"personal-bests",
              "uri":"https://www.speedrun.com/api/v1/users/qj29poxk/personal-bests"
            }
          ]
        },
        {
          "rel":"user",
          "id":"0jm0yko8",
          "names":{
            "international":"Ivancio",
            "japanese":null
          },
          "weblink":"https://www.speedrun.com/user/Ivancio",
          "name-style":{
            "style":"gradient",
            "color-from":{
              "light":"#E77471",
              "dark":"#E77471"
            },
            "color-to":{
              "light":"#E77471",
              "dark":"#E77471"
            }
          },
          "role":"user",
          "signup":"2017-09-03T03:35:50Z",
          "location":{
            "country":{
              "code":"cl",
              "names":{
                "international":"Chile",
                "japanese":null
              }
            }
          },
          "twitch":null,
          "hitbox":null,
          "youtube":null,
          "twitter":null,
          "speedrunslive":null,
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/users/0jm0yko8"
            },
            {
              "rel":"runs",
              "uri":"https://www.speedrun.com/api/v1/runs?user=0jm0yko8"
            },
            {
              "rel":"games",
              "uri":"https://www.speedrun.com/api/v1/games?moderator=0jm0yko8"
            },
            {
              "rel":"personal-bests",
              "uri":"https://www.speedrun.com/api/v1/users/0jm0yko8/personal-bests"
            }
          ]
        },
        {
          "rel":"user",
          "id":"y8dqzmj6",
          "names":{
            "international":"ImRiver",
            "japanese":null
          },
          "weblink":"https://www.speedrun.com/user/ImRiver",
          "name-style":{
            "style":"solid",
            "color":{
              "light":"#249BCE",
              "dark":"#44BBEE"
            }
          },
          "role":"user",
          "signup":"2015-07-17T13:26:33Z",
          "location":{
            "country":{
              "code":"ar",
              "names":{
                "international":"Argentina",
                "japanese":null
              }
            }
          },
          "twitch":null,
          "hitbox":null,
          "youtube":{
            "uri":"https://www.youtube.com/user/Serialageofempires"
          },
          "twitter":null,
          "speedrunslive":null,
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/users/y8dqzmj6"
            },
            {
              "rel":"runs",
              "uri":"https://www.speedrun.com/api/v1/runs?user=y8dqzmj6"
            },
            {
              "rel":"games",
              "uri":"https://www.speedrun.com/api/v1/games?moderator=y8dqzmj6"
            },
            {
              "rel":"personal-bests",
              "uri":"https://www.speedrun.com/api/v1/users/y8dqzmj6/personal-bests"
            }
          ]
        },
        {
          "rel":"user",
          "id":"qjn2l72j",
          "names":{
            "international":"empireboy2000",
            "japanese":null
          },
          "weblink":"https://www.speedrun.com/user/empireboy2000",
          "name-style":{
            "style":"gradient",
            "color-from":{
              "light":"#E77471",
              "dark":"#E77471"
            },
            "color-to":{
              "light":"#E77471",
              "dark":"#E77471"
            }
          },
          "role":"user",
          "signup":"2017-01-20T19:54:18Z",
          "location":{
            "country":{
              "code":"nl",
              "names":{
                "international":"Netherlands",
                "japanese":null
              }
            },
            "region":{
              "code":"nl/nh",
              "names":{
                "international":"North Holland, Netherlands",
                "japanese":null
              }
            }
          },
          "twitch":null,
          "hitbox":null,
          "youtube":null,
          "twitter":null,
          "speedrunslive":null,
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/users/qjn2l72j"
            },
            {
              "rel":"runs",
              "uri":"https://www.speedrun.com/api/v1/runs?user=qjn2l72j"
            },
            {
              "rel":"games",
              "uri":"https://www.speedrun.com/api/v1/games?moderator=qjn2l72j"
            },
            {
              "rel":"personal-bests",
              "uri":"https://www.speedrun.com/api/v1/users/qjn2l72j/personal-bests"
            }
          ]
        },
        {
          "rel":"user",
          "id":"v8lzdr4x",
          "names":{
            "international":"Obechosc",
            "japanese":null
          },
          "weblink":"https://www.speedrun.com/user/Obechosc",
          "name-style":{
            "style":"gradient",
            "color-from":{
              "light":"#7AB941",
              "dark":"#8AC951"
            },
            "color-to":{
              "light":"#7AB941",
              "dark":"#8AC951"
            }
          },
          "role":"user",
          "signup":"2017-09-26T07:17:31Z",
          "location":{
            "country":{
              "code":"us",
              "names":{
                "international":"United States",
                "japanese":null
              }
            },
            "region":{
              "code":"us/mo",
              "names":{
                "international":"Missouri, USA",
                "japanese":null
              }
            }
          },
          "twitch":{
            "uri":"https://www.twitch.tv/obechoscgames"
          },
          "hitbox":null,
          "youtube":{
            "uri":"https://www.youtube.com/channel/UCqlekFT-mD0bEBZw8Dk1viA"
          },
          "twitter":null,
          "speedrunslive":null,
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/users/v8lzdr4x"
            },
            {
              "rel":"runs",
              "uri":"https://www.speedrun.com/api/v1/runs?user=v8lzdr4x"
            },
            {
              "rel":"games",
              "uri":"https://www.speedrun.com/api/v1/games?moderator=v8lzdr4x"
            },
            {
              "rel":"personal-bests",
              "uri":"https://www.speedrun.com/api/v1/users/v8lzdr4x/personal-bests"
            }
          ]
        },
        {
          "rel":"guest",
          "name":"Sugagsr",
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/guests/Sugagsr"
            },
            {
              "rel":"runs",
              "uri":"https://www.speedrun.com/api/v1/runs?guest=Sugagsr"
            }
          ]
        },
        {
          "rel":"user",
          "id":"v18q6wjn",
          "names":{
            "international":"Mhmd_FVC",
            "japanese":null
          },
          "weblink":"https://www.speedrun.com/user/Mhmd_FVC",
          "name-style":{
            "style":"gradient",
            "color-from":{
              "light":"#000000",
              "dark":"#FFFFFF"
            },
            "color-to":{
              "light":"#808080",
              "dark":"#B8B8B8"
            }
          },
          "role":"user",
          "signup":"2014-03-25T00:12:52Z",
          "location":{
            "country":{
              "code":"us",
              "names":{
                "international":"United States",
                "japanese":null
              }
            },
            "region":{
              "code":"us/md",
              "names":{
                "international":"Maryland, USA",
                "japanese":null
              }
            }
          },
          "twitch":{
            "uri":"https://www.twitch.tv/Mhmd_FVC"
          },
          "hitbox":null,
          "youtube":{
            "uri":"https://www.youtube.com/c/MhmdFVC"
          },
          "twitter":{
            "uri":"https://www.twitter.com/srlMhmd"
          },
          "speedrunslive":null,
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/users/v18q6wjn"
            },
            {
              "rel":"runs",
              "uri":"https://www.speedrun.com/api/v1/runs?user=v18q6wjn"
            },
            {
              "rel":"games",
              "uri":"https://www.speedrun.com/api/v1/games?moderator=v18q6wjn"
            },
            {
              "rel":"personal-bests",
              "uri":"https://www.speedrun.com/api/v1/users/v18q6wjn/personal-bests"
            }
          ]
        },
        {
          "rel":"user",
          "id":"18q3o3dj",
          "names":{
            "international":"BellumZeldaDS",
            "japanese":null
          },
          "weblink":"https://www.speedrun.com/user/BellumZeldaDS",
          "name-style":{
            "style":"gradient",
            "color-from":{
              "light":"#DAA520",
              "dark":"#F0C03E"
            },
            "color-to":{
              "light":"#DAA520",
              "dark":"#F0C03E"
            }
          },
          "role":"user",
          "signup":"2016-09-04T13:49:29Z",
          "location":{
            "country":{
              "code":"fr",
              "names":{
                "international":"France",
                "japanese":null
              }
            }
          },
          "twitch":{
            "uri":"https://www.twitch.tv/bellumzeldads"
          },
          "hitbox":null,
          "youtube":{
            "uri":"https://www.youtube.com/channel/UCQCpKqdrrfslhfzr3cGGxdQ"
          },
          "twitter":null,
          "speedrunslive":null,
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/users/18q3o3dj"
            },
            {
              "rel":"runs",
              "uri":"https://www.speedrun.com/api/v1/runs?user=18q3o3dj"
            },
            {
              "rel":"games",
              "uri":"https://www.speedrun.com/api/v1/games?moderator=18q3o3dj"
            },
            {
              "rel":"personal-bests",
              "uri":"https://www.speedrun.com/api/v1/users/18q3o3dj/personal-bests"
            }
          ]
        },
        {
          "rel":"user",
          "id":"v8141658",
          "names":{
            "international":"l_need_a_doctor",
            "japanese":null
          },
          "weblink":"https://www.speedrun.com/user/l_need_a_doctor",
          "name-style":{
            "style":"gradient",
            "color-from":{
              "light":"#900090",
              "dark":"#A010A0"
            },
            "color-to":{
              "light":"#900090",
              "dark":"#A010A0"
            }
          },
          "role":"user",
          "signup":"2016-01-31T22:41:42Z",
          "location":{
            "country":{
              "code":"pl",
              "names":{
                "international":"Poland",
                "japanese":null
              }
            }
          },
          "twitch":{
            "uri":"https://www.twitch.tv/l_need_a_doctor"
          },
          "hitbox":null,
          "youtube":{
            "uri":"https://www.youtube.com/user/mnmaniek011"
          },
          "twitter":null,
          "speedrunslive":null,
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/users/v8141658"
            },
            {
              "rel":"runs",
              "uri":"https://www.speedrun.com/api/v1/runs?user=v8141658"
            },
            {
              "rel":"games",
              "uri":"https://www.speedrun.com/api/v1/games?moderator=v8141658"
            },
            {
              "rel":"personal-bests",
              "uri":"https://www.speedrun.com/api/v1/users/v8141658/personal-bests"
            }
          ]
        },
        {
          "rel":"user",
          "id":"dx3l24qx",
          "names":{
            "international":"VonDerVogelweide",
            "japanese":null
          },
          "weblink":"https://www.speedrun.com/user/VonDerVogelweide",
          "name-style":{
            "style":"gradient",
            "color-from":{
              "light":"#EE2222",
              "dark":"#EE4444"
            },
            "color-to":{
              "light":"#EE2222",
              "dark":"#EE4444"
            }
          },
          "role":"user",
          "signup":"2018-07-18T18:35:22Z",
          "location":{
            "country":{
              "code":"at",
              "names":{
                "international":"Austria",
                "japanese":null
              }
            }
          },
          "twitch":null,
          "hitbox":null,
          "youtube":{
            "uri":"https://www.youtube.com/channel/UCnBFEBAyiSSzKXOs8CRr-xg%3Fview_assubscriber"
          },
          "twitter":null,
          "speedrunslive":null,
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/users/dx3l24qx"
            },
            {
              "rel":"runs",
              "uri":"https://www.speedrun.com/api/v1/runs?user=dx3l24qx"
            },
            {
              "rel":"games",
              "uri":"https://www.speedrun.com/api/v1/games?moderator=dx3l24qx"
            },
            {
              "rel":"personal-bests",
              "uri":"https://www.speedrun.com/api/v1/users/dx3l24qx/personal-bests"
            }
          ]
        },
        {
          "rel":"user",
          "id":"18vyq3v8",
          "names":{
            "international":"BladeGondolin",
            "japanese":null
          },
          "weblink":"https://www.speedrun.com/user/BladeGondolin",
          "name-style":{
            "style":"gradient",
            "color-from":{
              "light":"#808080",
              "dark":"#B8B8B8"
            },
            "color-to":{
              "light":"#808080",
              "dark":"#B8B8B8"
            }
          },
          "role":"user",
          "signup":"2017-12-16T17:27:09Z",
          "location":{
            "country":{
              "code":"gb/sct",
              "names":{
                "international":"Scotland",
                "japanese":null
              }
            },
            "region":{
              "code":"gb/sct/abd",
              "names":{
                "international":"Aberdeen, Scotland",
                "japanese":null
              }
            }
          },
          "twitch":null,
          "hitbox":null,
          "youtube":null,
          "twitter":null,
          "speedrunslive":null,
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/users/18vyq3v8"
            },
            {
              "rel":"runs",
              "uri":"https://www.speedrun.com/api/v1/runs?user=18vyq3v8"
            },
            {
              "rel":"games",
              "uri":"https://www.speedrun.com/api/v1/games?moderator=18vyq3v8"
            },
            {
              "rel":"personal-bests",
              "uri":"https://www.speedrun.com/api/v1/users/18vyq3v8/personal-bests"
            }
          ]
        },
        {
          "rel":"user",
          "id":"e8e22d78",
          "names":{
            "international":"MikuRuns",
            "japanese":null
          },
          "weblink":"https://www.speedrun.com/user/MikuRuns",
          "name-style":{
            "style":"gradient",
            "color-from":{
              "light":"#249BCE",
              "dark":"#44BBEE"
            },
            "color-to":{
              "light":"#249BCE",
              "dark":"#44BBEE"
            }
          },
          "role":"user",
          "signup":"2018-11-08T17:45:06Z",
          "location":{
            "country":{
              "code":"cr",
              "names":{
                "international":"Costa Rica",
                "japanese":null
              }
            }
          },
          "twitch":null,
          "hitbox":null,
          "youtube":{
            "uri":"https://www.youtube.com/channel/UCEoMx9MM5XvfEf_VNozNfcw"
          },
          "twitter":{
            "uri":"https://www.twitter.com/qaaq50409126"
          },
          "speedrunslive":null,
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/users/e8e22d78"
            },
            {
              "rel":"runs",
              "uri":"https://www.speedrun.com/api/v1/runs?user=e8e22d78"
            },
            {
              "rel":"games",
              "uri":"https://www.speedrun.com/api/v1/games?moderator=e8e22d78"
            },
            {
              "rel":"personal-bests",
              "uri":"https://www.speedrun.com/api/v1/users/e8e22d78/personal-bests"
            }
          ]
        }
      ]
    },
    "regions":{
      "data":[

      ]
    },
    "platforms":{
      "data":[
        {
          "id":"8gej2n93",
          "name":"PC",
          "released":1970,
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/platforms/8gej2n93"
            },
            {
              "rel":"games",
              "uri":"https://www.speedrun.com/api/v1/games?platform=8gej2n93"
            },
            {
              "rel":"runs",
              "uri":"https://www.speedrun.com/api/v1/runs?platform=8gej2n93"
            }
          ]
        }
      ]
    },
    "variables":{
      "data":[
        {
          "id":"q38drxl0",
          "name":"Game Version",
          "category":null,
          "scope":{
            "type":"all-levels"
          },
          "mandatory":true,
          "user-defined":false,
          "obsoletes":true,
          "values":{
            "_note":"`choices` is deprecated, please use `values` instead",
            "choices":{
              "4lx5yj12":"AoK",
              "814o2wqd":"AoC",
              "p12vzvqx":"HD Edition"
            },
            "values":{
              "4lx5yj12":{
                "label":"AoK"
              },
              "814o2wqd":{
                "label":"AoC"
              },
              "p12vzvqx":{
                "label":"HD Edition"
              }
            },
            "default":null
          },
          "is-subcategory":false,
          "links":[
            {
              "rel":"self",
              "uri":"https://www.speedrun.com/api/v1/variables/q38drxl0"
            },
            {
              "rel":"game",
              "uri":"https://www.speedrun.com/api/v1/games/xldev513"
            }
          ]
        }
      ]
    }
  }
}
JSON
        );
        $leaderboard = $client->leaderboards()->getByGameCategory('foo', 'bar');

        self::assertSame('z11pewwz', $leaderboard->getRuns()[0]->getRun()->getId());
        self::assertSame('y67299qm', $leaderboard->getRuns()[12]->getRun()->getId());
    }
}
