<?php
namespace Dsinn\SrcomApi\Tests;

class LeaderboardsTest extends TestCase
{
    /**
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function testGetByGameCategory()
    {
        $client = $this->getClient(<<<'JSON'
{
  "data":{
    "weblink":"https://www.speedrun.com/aoe2/full_game#All_Campaigns",
    "game":"xldev513",
    "category":"rklg3rdn",
    "level":null,
    "platform":null,
    "region":null,
    "emulators":null,
    "video-only":false,
    "timing":"realtime",
    "values":{

    },
    "runs":[
      {
        "place":1,
        "run":{
          "id":"yw1nj0nz",
          "weblink":"https://www.speedrun.com/aoe2/run/yw1nj0nz",
          "game":"xldev513",
          "level":null,
          "category":"rklg3rdn",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=F1z59gYX7Jk"
              }
            ]
          },
          "comment":"Bad levels:\r\nJoA5 - Transport ship never landed, so no trigger for the end never loaded?\r\nSala2 - Bad ships\r\nBB3  - Myself playing super bad\r\nAtt1 -  Destroy monastery then market. noted.\r\nMonte 2 - Bad luck on the red army killing my rams and bad play.\r\nHastings - Needed to play it on AoE2HD not AoC\r\nVindlandsaga - Longboats wrecked me.",
          "status":{
            "status":"verified",
            "examiner":"v18q6wjn",
            "verify-date":"2018-01-05T03:22:57Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"18vqvejl",
              "uri":"https://www.speedrun.com/api/v1/users/18vqvejl"
            }
          ],
          "date":"2018-01-02",
          "submitted":"2018-01-02T22:04:03Z",
          "times":{
            "primary":"PT7H3M43S",
            "primary_t":25423,
            "realtime":"PT7H3M43S",
            "realtime_t":25423,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":{
            "rel":"splits.io",
            "uri":"https://splits.io/api/v3/runs/23gp"
          },
          "values":{
            "m5ly6jn4":"xqke89q9"
          }
        }
      },
      {
        "place":2,
        "run":{
          "id":"pzgkj6ey",
          "weblink":"https://www.speedrun.com/aoe2/run/pzgkj6ey",
          "game":"xldev513",
          "level":null,
          "category":"rklg3rdn",
          "videos":{
            "links":[
              {
                "uri":"http://www.twitch.tv/adam_ak/v/4191464"
              },
              {
                "uri":"http://www.twitch.tv/adam_ak/v/4191449"
              }
            ]
          },
          "comment":"part 2: http://www.twitch.tv/adam_ak/v/4191464\r\n\r\nResult of the race with Mhmd and Dawned. Montezuma and BoC were a mess -- rest was OK. Will improve :v)",
          "status":{
            "status":"verified",
            "examiner":"v18q6wjn",
            "verify-date":"2015-05-10T12:09:40Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"gpj0mxwr",
              "uri":"https://www.speedrun.com/api/v1/users/gpj0mxwr"
            }
          ],
          "date":"2015-04-11",
          "submitted":"2015-04-20T13:41:10Z",
          "times":{
            "primary":"PT27H55M24S",
            "primary_t":100524,
            "realtime":"PT27H55M24S",
            "realtime_t":100524,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "m5ly6jn4":"p12z471x"
          }
        }
      }
    ],
    "links":[
      {
        "rel":"game",
        "uri":"https://www.speedrun.com/api/v1/games/xldev513"
      },
      {
        "rel":"category",
        "uri":"https://www.speedrun.com/api/v1/categories/rklg3rdn"
      }
    ]
  }
}
JSON
        );
        $leaderboard = $client->leaderboards()->getByGameCategory('foo', 'bar');

        self::assertSame('yw1nj0nz', $leaderboard->getRuns()[0]->getRun()->getId());
        self::assertSame('pzgkj6ey', $leaderboard->getRuns()[1]->getRun()->getId());
    }

    /**
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function testGetByLevelCategory()
    {
        $client = $this->getClient(<<<'JSON'
{
  "data":{
    "weblink":"https://www.speedrun.com/aoe2/William_Wallace_Marching_and_Fighting#Standard",
    "game":"xldev513",
    "category":"xk9le4k0",
    "level":"rdqz4kdx",
    "platform":null,
    "region":null,
    "emulators":null,
    "video-only":false,
    "timing":"realtime",
    "values":{

    },
    "runs":[
      {
        "place":1,
        "run":{
          "id":"z11pewwz",
          "weblink":"https://www.speedrun.com/aoe2/run/z11pewwz",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=Lx0ug-pw7u0"
              }
            ]
          },
          "comment":"IGT 1:59",
          "status":{
            "status":"verified",
            "examiner":"v18q6wjn",
            "verify-date":"2018-11-03T16:50:18Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"18vqvejl",
              "uri":"https://www.speedrun.com/api/v1/users/18vqvejl"
            }
          ],
          "date":"2018-11-02",
          "submitted":"2018-11-02T18:41:09Z",
          "times":{
            "primary":"PT1M19S",
            "primary_t":79,
            "realtime":"PT1M19S",
            "realtime_t":79,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"p12vzvqx"
          }
        }
      },
      {
        "place":2,
        "run":{
          "id":"y6712rqm",
          "weblink":"https://www.speedrun.com/aoe2/run/y6712rqm",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://youtu.be/OG4_FuNfiKo"
              }
            ]
          },
          "comment":"Honestly, I was just going for a top 3 run, but then I realized with chaz\u0027s catchup trick using the knight and some really precise timing this was possible.",
          "status":{
            "status":"verified",
            "examiner":"v18q6wjn",
            "verify-date":"2018-05-02T00:48:03Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"dx3rnlkx",
              "uri":"https://www.speedrun.com/api/v1/users/dx3rnlkx"
            }
          ],
          "date":"2018-04-28",
          "submitted":"2018-04-28T03:29:56Z",
          "times":{
            "primary":"PT1M21S",
            "primary_t":81,
            "realtime":"PT1M21S",
            "realtime_t":81,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"p12vzvqx"
          }
        }
      },
      {
        "place":3,
        "run":{
          "id":"pydg6d0y",
          "weblink":"https://www.speedrun.com/aoe2/run/pydg6d0y",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=x3IZzh_AB7g"
              }
            ]
          },
          "comment":"2:04 IGT",
          "status":{
            "status":"verified",
            "examiner":"qj29poxk",
            "verify-date":"2016-04-24T15:53:00Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"qj29poxk",
              "uri":"https://www.speedrun.com/api/v1/users/qj29poxk"
            }
          ],
          "date":"2016-04-24",
          "submitted":"2016-04-24T15:53:00Z",
          "times":{
            "primary":"PT1M22S",
            "primary_t":82,
            "realtime":"PT1M22S",
            "realtime_t":82,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"814o2wqd"
          }
        }
      },
      {
        "place":4,
        "run":{
          "id":"y8q6v8ny",
          "weblink":"https://www.speedrun.com/aoe2/run/y8q6v8ny",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=cO4euLU2k-c"
              }
            ]
          },
          "comment":"Gracias a River y SiFly por la ruta.",
          "status":{
            "status":"verified",
            "examiner":"qj29poxk",
            "verify-date":"2017-12-15T18:07:11Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"0jm0yko8",
              "uri":"https://www.speedrun.com/api/v1/users/0jm0yko8"
            }
          ],
          "date":"2017-12-14",
          "submitted":"2017-12-15T02:18:53Z",
          "times":{
            "primary":"PT1M23S",
            "primary_t":83,
            "realtime":"PT1M23S",
            "realtime_t":83,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"p12vzvqx"
          }
        }
      },
      {
        "place":5,
        "run":{
          "id":"y8q6rvwy",
          "weblink":"https://www.speedrun.com/aoe2/run/y8q6rvwy",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=ZQWdEoUGVsY"
              }
            ]
          },
          "comment":null,
          "status":{
            "status":"verified",
            "examiner":"qj29poxk",
            "verify-date":"2017-12-14T18:26:22Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"y8dqzmj6",
              "uri":"https://www.speedrun.com/api/v1/users/y8dqzmj6"
            }
          ],
          "date":"2017-12-14",
          "submitted":"2017-12-14T03:16:49Z",
          "times":{
            "primary":"PT1M25S",
            "primary_t":85,
            "realtime":"PT1M25S",
            "realtime_t":85,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"p12vzvqx"
          }
        }
      },
      {
        "place":6,
        "run":{
          "id":"6yj06v7z",
          "weblink":"https://www.speedrun.com/aoe2/run/6yj06v7z",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://youtu.be/Fv0ZoDzodW8"
              }
            ]
          },
          "comment":"The timing wasn\u0027t perfect, will do better someday !",
          "status":{
            "status":"verified",
            "examiner":"v18q6wjn",
            "verify-date":"2017-02-23T18:44:32Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"qjn2l72j",
              "uri":"https://www.speedrun.com/api/v1/users/qjn2l72j"
            }
          ],
          "date":"2017-02-23",
          "submitted":"2017-02-23T16:19:35Z",
          "times":{
            "primary":"PT1M26S",
            "primary_t":86,
            "realtime":"PT1M26S",
            "realtime_t":86,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"p12vzvqx"
          }
        }
      },
      {
        "place":6,
        "run":{
          "id":"mrq6k64y",
          "weblink":"https://www.speedrun.com/aoe2/run/mrq6k64y",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=K0eA1AUNlv8\u0026feature=youtu.be"
              }
            ]
          },
          "comment":null,
          "status":{
            "status":"verified",
            "examiner":"v18q6wjn",
            "verify-date":"2017-09-29T22:23:19Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"v8lzdr4x",
              "uri":"https://www.speedrun.com/api/v1/users/v8lzdr4x"
            }
          ],
          "date":"2017-09-27",
          "submitted":"2017-09-27T04:40:35Z",
          "times":{
            "primary":"PT1M26S",
            "primary_t":86,
            "realtime":"PT1M26S",
            "realtime_t":86,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"p12vzvqx"
          }
        }
      },
      {
        "place":8,
        "run":{
          "id":"oy2eq97y",
          "weblink":"https://www.speedrun.com/aoe2/run/oy2eq97y",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=MUWEpqim9Ec"
              }
            ]
          },
          "comment":null,
          "status":{
            "status":"verified",
            "examiner":"qj29poxk",
            "verify-date":"2016-03-13T14:04:55Z"
          },
          "players":[
            {
              "rel":"guest",
              "name":"Sugagsr",
              "uri":"https://www.speedrun.com/api/v1/guests/Sugagsr"
            }
          ],
          "date":null,
          "submitted":"2016-03-13T14:04:55Z",
          "times":{
            "primary":"PT1M28S",
            "primary_t":88,
            "realtime":"PT1M28S",
            "realtime_t":88,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"4lx5yj12"
          }
        }
      },
      {
        "place":9,
        "run":{
          "id":"8y8q8e5y",
          "weblink":"https://www.speedrun.com/aoe2/run/8y8q8e5y",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=0dsIrnA3JJM"
              }
            ]
          },
          "comment":"not bad",
          "status":{
            "status":"verified",
            "examiner":null,
            "verify-date":null
          },
          "players":[
            {
              "rel":"user",
              "id":"v18q6wjn",
              "uri":"https://www.speedrun.com/api/v1/users/v18q6wjn"
            }
          ],
          "date":"2014-12-23",
          "submitted":"2014-12-23T10:34:56Z",
          "times":{
            "primary":"PT1M30S",
            "primary_t":90,
            "realtime":"PT1M30S",
            "realtime_t":90,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{

          }
        }
      },
      {
        "place":9,
        "run":{
          "id":"zn4png7m",
          "weblink":"https://www.speedrun.com/aoe2/run/zn4png7m",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=FyTAQN3eKJk"
              }
            ]
          },
          "comment":":(",
          "status":{
            "status":"verified",
            "examiner":"v18q6wjn",
            "verify-date":"2018-11-03T16:51:32Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"18q3o3dj",
              "uri":"https://www.speedrun.com/api/v1/users/18q3o3dj"
            }
          ],
          "date":"2018-11-02",
          "submitted":"2018-11-02T15:40:15Z",
          "times":{
            "primary":"PT1M30S",
            "primary_t":90,
            "realtime":"PT1M30S",
            "realtime_t":90,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"814o2wqd"
          }
        }
      },
      {
        "place":11,
        "run":{
          "id":"emkvqo3y",
          "weblink":"https://www.speedrun.com/aoe2/run/emkvqo3y",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=UG3Ye-Rvt80"
              }
            ]
          },
          "comment":"2:17 IGT.",
          "status":{
            "status":"verified",
            "examiner":"qj29poxk",
            "verify-date":"2016-05-13T11:03:52Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"v8141658",
              "uri":"https://www.speedrun.com/api/v1/users/v8141658"
            }
          ],
          "date":"2016-05-13",
          "submitted":"2016-05-13T10:53:43Z",
          "times":{
            "primary":"PT1M31S",
            "primary_t":91,
            "realtime":"PT1M31S",
            "realtime_t":91,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"814o2wqd"
          }
        }
      },
      {
        "place":12,
        "run":{
          "id":"z039rv8z",
          "weblink":"https://www.speedrun.com/aoe2/run/z039rv8z",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://youtu.be/NSA9sOdvHm4"
              }
            ]
          },
          "comment":null,
          "status":{
            "status":"verified",
            "examiner":"v18q6wjn",
            "verify-date":"2018-08-11T23:14:26Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"dx3l24qx",
              "uri":"https://www.speedrun.com/api/v1/users/dx3l24qx"
            }
          ],
          "date":"2018-08-09",
          "submitted":"2018-08-09T10:28:00Z",
          "times":{
            "primary":"PT1M32S",
            "primary_t":92,
            "realtime":"PT1M32S",
            "realtime_t":92,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"p12vzvqx"
          }
        }
      },
      {
        "place":13,
        "run":{
          "id":"y67299qm",
          "weblink":"https://www.speedrun.com/aoe2/run/y67299qm",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=Jyh3INk-jS4"
              }
            ]
          },
          "comment":"First ever run, just getting video/split thing sorted right now, will worry about times later! :D",
          "status":{
            "status":"verified",
            "examiner":"qj29poxk",
            "verify-date":"2017-12-16T18:30:36Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"18vyq3v8",
              "uri":"https://www.speedrun.com/api/v1/users/18vyq3v8"
            }
          ],
          "date":"2017-12-16",
          "submitted":"2017-12-16T17:31:21Z",
          "times":{
            "primary":"PT1M38S",
            "primary_t":98,
            "realtime":"PT1M38S",
            "realtime_t":98,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"p12vzvqx"
          }
        }
      },
      {
        "place":14,
        "run":{
          "id":"mr8r7x4y",
          "weblink":"https://www.speedrun.com/aoe2/run/mr8r7x4y",
          "game":"xldev513",
          "level":"rdqz4kdx",
          "category":"xk9le4k0",
          "videos":{
            "links":[
              {
                "uri":"https://www.youtube.com/watch?v=Kvm3gxE5Dhs"
              }
            ]
          },
          "comment":null,
          "status":{
            "status":"verified",
            "examiner":"v18q6wjn",
            "verify-date":"2018-11-10T20:35:29Z"
          },
          "players":[
            {
              "rel":"user",
              "id":"e8e22d78",
              "uri":"https://www.speedrun.com/api/v1/users/e8e22d78"
            }
          ],
          "date":"2018-11-10",
          "submitted":"2018-11-10T18:38:01Z",
          "times":{
            "primary":"PT2M9S",
            "primary_t":129,
            "realtime":"PT2M9S",
            "realtime_t":129,
            "realtime_noloads":null,
            "realtime_noloads_t":0,
            "ingame":null,
            "ingame_t":0
          },
          "system":{
            "platform":"8gej2n93",
            "emulated":false,
            "region":null
          },
          "splits":null,
          "values":{
            "q38drxl0":"4lx5yj12"
          }
        }
      }
    ],
    "links":[
      {
        "rel":"game",
        "uri":"https://www.speedrun.com/api/v1/games/xldev513"
      },
      {
        "rel":"category",
        "uri":"https://www.speedrun.com/api/v1/categories/xk9le4k0"
      },
      {
        "rel":"level",
        "uri":"https://www.speedrun.com/api/v1/levels/rdqz4kdx"
      }
    ]
  }
}
JSON
        );
        $leaderboard = $client->leaderboards()->getByGameCategory('foo', 'bar');

        self::assertSame('z11pewwz', $leaderboard->getRuns()[0]->getRun()->getId());
        self::assertSame('y67299qm', $leaderboard->getRuns()[12]->getRun()->getId());
    }
}
